### ISSUE TITLE
reference-de repository is not receiving the automated issue reports

### ISSUE THREAD

**Issue by per1234** [arduino/reference-de#60]
Whenever the reference-en repository is updated, the reference-es, reference-it, reference-jp, reference-ko, and reference-pt repositories receive automated issue reports. These issue reports provide a useful "to-do" list. Now that the reference-de repository has active translation work, I think it should definitely receive these automated issue reports as well.

Related: https://github.com/arduino/reference-en/issues/288

**Comment by SeppPenner** [comment]
@smellai Can you fix this?

**Comment by mastrolinux** [comment]
It should work now but I cannot test it, we have to wait some changes in the en language and see what happens here.

**Comment by SeppPenner** [comment]
Ok, thank you.

**Comment by per1234** [comment]
@mastrolinux a [PR](https://github.com/arduino/reference-en/pull/388) was merged in reference-en and reference-es/it/jp/ko/pt received automated issue reports, but not this repo. So I think it's still not working.

I notice this repo has no `automated` [label](https://github.com/arduino/reference-de/labels). I know that [caused ](https://github.com/arduino/reference-en/issues/288)the automated issues to initially not work for reference-ko so I suspect that's the problem here too.

**Comment by SeppPenner** [comment]
@per1234 I think this is correct. My PR on the english repo does not provide a new issue here...

**Comment by SeppPenner** [comment]
We will see if it works, when https://github.com/arduino/reference-en/pull/390 is merged.

**Comment by mastrolinux** [comment]
Right, I just added that label!
